language: rust
rust:
  - stable

arch:
  - amd64
  - arm64

matrix:
  include:
    - os: osx
      arch: amd64
    - os: linux
      arch: amd64
    - os: linux
      arch: arm64

compiler:
  - clang

script:
  - cargo test --verbose --no-default-features
  - cargo test --verbose --no-default-features --features="force_backtrace"
  - cargo test --verbose --no-default-features --features="derive_display"
  - cargo test --verbose --no-default-features --features="force_backtrace,derive_display"

  - cargo test --verbose --release --no-default-features
  - cargo test --verbose --release --no-default-features --features="force_backtrace"
  - cargo test --verbose --release --no-default-features --features="derive_display"
  - cargo test --verbose --release --no-default-features --features="force_backtrace,derive_display"
