language: rust
# FIXME: Use stable once https://github.com/rust-lang/rust/pull/72981 has been stabilized
rust:
  - nightly

arch:
  - amd64
  - arm64

matrix:
  include:
    - os: osx
      arch: amd64
    - os: linux
      arch: amd64
    - os: linux
      arch: arm64

compiler:
  - clang

# FIXME: Remove +nightly once https://github.com/rust-lang/rust/pull/72981 has been stabilized
script:
  - cargo +nightly test --verbose --no-default-features
  - cargo +nightly test --verbose --no-default-features --features="force_backtrace"
  - cargo +nightly test --verbose --no-default-features --features="derive_display"
  - cargo +nightly test --verbose --no-default-features --features="force_backtrace,derive_display"

  - cargo +nightly test --verbose --release --no-default-features
  - cargo +nightly test --verbose --release --no-default-features --features="force_backtrace"
  - cargo +nightly test --verbose --release --no-default-features --features="derive_display"
  - cargo +nightly test --verbose --release --no-default-features --features="force_backtrace,derive_display"
